-- Criar a tabela de fornecedores com tipos int8
CREATE TABLE IF NOT EXISTS public.suppliers (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    company_id int8 NOT NULL REFERENCES public.companys(id) ON DELETE CASCADE,
    cnpj TEXT,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Definir a chave primária composta
    PRIMARY KEY (id, company_id)
);

-- Ativar RLS (Segurança de linha)
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- Índice para busca rápida por CNPJ (opcional, mas recomendado)
CREATE UNIQUE INDEX idx_suppliers_cnpj_company ON public.suppliers(cnpj, company_id);

CREATE TRIGGER update_suppliers_updated_at
    BEFORE UPDATE ON public.suppliers
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();