-- 1. Criação da Tabela
create table public.company_branches (
  id bigint generated by default as identity not null,
  cnpj text not null,
  company_id bigint not null,
  created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
  updated_at timestamp with time zone not null default (now() at time zone 'utc'::text),

  -- Constraints
  constraint company_branches_pkey primary key (id),
  constraint company_branches_cnpj_key unique (cnpj),
  constraint company_branches_company_id_fkey 
    foreign key (company_id) references public.companys (id) 
    on delete cascade
) tablespace pg_default;

-- 2. Trigger para atualizar o updated_at automaticamente
create trigger trg_set_updated_at_company_branches
  before update on public.company_branches
  for each row
  execute function set_updated_at();

-- 3. Trigger para preencher o company_id a partir dos metadados do usuário
create trigger trg_set_company_id_company_branches
  before insert or update on public.company_branches
  for each row
  execute function set_company_id_from_metadata();