CREATE TABLE IF NOT EXISTS public.competitor_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    company_id BIGINT NOT NULL,
    
    competitor_id INT NOT NULL REFERENCES public.competitors(id) ON DELETE CASCADE,
    
    branch_id INT NOT NULL,

    CONSTRAINT fk_cb_company 
        FOREIGN KEY (company_id) 
        REFERENCES public.companys(id) 
        ON DELETE CASCADE,

    CONSTRAINT fk_cb_branch 
        FOREIGN KEY (branch_id, company_id) 
        REFERENCES public.company_branches(id, company_id) 
        ON DELETE CASCADE,

    CONSTRAINT unique_competitor_branch UNIQUE(competitor_id, branch_id)
);

ALTER TABLE public.competitor_branches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Somente sua Empresa" 
ON public.competitor_branches
FOR ALL 
USING (
    company_id = (SELECT get_my_company())
)
WITH CHECK (
    company_id = (SELECT get_my_company())
);

CREATE INDEX idx_cb_company ON public.competitor_branches(company_id);
CREATE INDEX idx_cb_competitor ON public.competitor_branches(competitor_id);
CREATE INDEX idx_cb_branch_composite ON public.competitor_branches(branch_id, company_id);