-- Criar a tabela de concorrentes
CREATE TABLE IF NOT EXISTS public.competitors (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    company_id int8 NOT NULL REFERENCES public.companys(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

    -- Definir a chave primária composta
    PRIMARY KEY (id, company_id)
);

-- Ativar RLS (Segurança de linha)
ALTER TABLE public.competitors ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_competitors_updated_at
    BEFORE UPDATE ON public.competitors
    FOR EACH ROW
    EXECUTE PROCEDURE set_updated_at();