CREATE TABLE IF NOT EXISTS public.product_margin_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES public.companys(id) ON DELETE CASCADE,
    branche_id int4 NOT NULL,
    product_id INT NOT NULL,
    margin NUMERIC(5,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    CONSTRAINT fk_pmb_branch 
        FOREIGN KEY (branche_id, company_id) 
        REFERENCES public.company_branches(id, company_id) ON DELETE CASCADE,

    CONSTRAINT fk_pmb_product
        FOREIGN KEY (product_id, company_id)
        REFERENCES public.products(id, company_id) ON DELETE CASCADE,

    CONSTRAINT unique_store_product_margin UNIQUE(product_id, branche_id, company_id)
);

ALTER TABLE public.product_margin_branches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Somente sua Empresa" 
ON public.product_margin_branches
FOR ALL 
TO authenticated
USING (
    company_id = (SELECT get_my_company())
)
WITH CHECK (
    company_id = (SELECT get_my_company())
);

CREATE INDEX idx_pmb_company_product ON public.product_margin_branches(company_id, product_id);
CREATE INDEX idx_pmb_company_branch ON public.product_margin_branches(company_id, branche_id);

DROP TRIGGER IF EXISTS trg_set_updated_at_product_margin_branches
ON public.product_margin_branches;

CREATE TRIGGER trg_set_updated_at_product_margin_branches
BEFORE UPDATE
ON public.product_margin_branches
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();